version: '3'
services:
  web:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres@postgres/postgres
      - CELERY_BACKEND=redis://redis
      - CELERY_BROKER=redis://redis
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - ${PORT:-5000}:5000
    depends_on:
      - postgres
    volumes:
      - .:/app
  postgres:
    image: "postgres"
  redis:
    image: "redis"
  