version: '3'
services:
  web:
    build: .
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - ${PORT:-5000}:5000
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
  postgres:
    image: "postgres"
  redis:
    image: redis:3.2
    restart: always
    ports:
      - "6378:6379"