version: '3'
services:
  web:
    build: .
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - ${PORT:-5000}:5000
    depends_on:
      - postgres
    volumes:
      - .:/app
  postgres:
    image: "postgres"
  redis:
    image: "redis"
  