name: countries-of-interest-service
channels:
- defaults
dependencies:
- flask=1.1.1
- psycopg2=2.8.4
- pyyaml=5.2
- werkzeug=0.16.0
- yaml
- curl
- openssl=1.1.1
- pytest=5.3.2
- pytest-cov=2.8.1
- python=3.6.8
- pip==19.3.1
- pip:
  - APScheduler==3.*
  - black==19.10b0
  - celery==4.4.0
  - codecov==2.0.15
  - flake8-import-order==0.18.1
  - flake8==3.7.9
  - flask-oauthlib==0.9.5
  - flask-security==3.0.0
  - flask-script==2.0.5
  - flask-sqlalchemy==2.4.1
  - gunicorn==20.*
  - mohawk==1.1.0
  - numpy==1.*
  - pandas==0.*
  - requests-oauthlib==1.3.0
  - redis==3.3.11
  - sqlalchemy==1.3.12
  - sqlalchemy-utils==0.36.1
  - watchdog==0.9.0
