flask:
  env: $ENV{FLASK_ENV, dev}
app:
  secret_key: $ENV{APP_SECRET_KEY, random_string}
  database_url: $ENV{DATABASE_URL, postgresql://postgres@postgres/postgres}
  pagination_size: $ENV{PAGINATION_SIZE, 50}
  run_scheduler: $ENV{RUN_SCHEDULER, False}
  hawk_enabled: $ENV{HAWK_ENABLED, True}
sso:
  host: $ENV{ABC_BASE_URL, https://sso.trade.gov.uk}
  abc_client_id: $ENV{ABC_CLIENT_ID, sso_client_id}
  abc_client_secret: $ENV{ABC_CLIENT_SECRET, sso_client_secret}
dataworkspace:
  host: $ENV{DATAWORKSPACE_HOST, localapps.com:8000}
  hawk_client_id: $ENV{DATAWORKSPACE_HAWK_CLIENT_ID, dataworkspace_client_id}
  hawk_client_key: $ENV{DATAWORKSPACE_HAWK_CLIENT_KEY, dataworkspace_client_key}
dataflow:
  host: $ENV{DATAFLOW_HOST, }
  hawk_client_id: $ENV{DATAFLOW_HAWK_CLIENT_ID, dataflow_client_id}
  hawk_client_key: $ENV{DATAFLOW_HAWK_CLIENT_KEY, dataflow_client_id}
cache:
  host: $ENV{CACHE_HOST, redis://redis}
  port: $ENV{CACHE_PORT, 6379}
  password: $ENV{CACHE_PWD, }
  ssl: $ENV{CACHE_SSL, True}


